<main class="container-fluid mt-3">
  <form action="edit" method="post" enctype="multipart/form-data" class="text-center">
    <div class="mb-3">
      <input type="number" name="id_movie" class="form-control" readonly value="<?= htmlspecialchars($movie->id_movie) ?>">
    </div>
    <div class="mb-3">
      <input type="text" name="title" class="form-control" required value="<?= htmlspecialchars($movie->title) ?>">
    </div>
    <div class="mb-3">
      <input type="file" name="poster_path" class="form-control" required>
    </div>
    <div class="mb-3">
      <input type="date" name="release_date" class="form-control" required value="<?= htmlspecialchars($movie->release_date) ?>">
    </div>
    <div class="mb-3">
      <textarea name="overview" class="form-control" rows="3" required><?= htmlspecialchars($movie->overview) ?></textarea>
    </div>
    <div class="mb-3">
      <input type="text" name="company" class="form-control" required value="<?= htmlspecialchars($movie->company) ?>">
    </div>
    <select class="form-select mb-3" name="id_genre">
      <option disabled>genre</option>
      <?php foreach ($genres as $key => $genre) : ?>
        <option <?php if ($genre->main_genre == $movie->main_genre) : ?>selected<?php endif ?>
          value="<?= $genre->id_genre ?>"><?= $genre->main_genre ?></option>
      <?php endforeach ?>
    </select>
    <button type="submit" class="btn btn-primary">Confirm</button>
    <a href="showList" class="btn btn-secondary">Cancel</a>
  </form>
</main>