<main class="container-fluid mt-3">
  <form action="add" method="post" class="text-center">
    <div class="mb-3">
      <input type="number" name="id_movie" class="form-control" required placeholder="id_movie">
    </div>
    <div class="mb-3">
      <input type="text" name="title" class="form-control" required placeholder="title">
    </div>
    <div class="mb-3">
      <input type="text" name="poster_path" class="form-control" required placeholder="poster_path">
    </div>
    <div class="mb-3">
      <input type="date" name="release_date" class="form-control" required placeholder="release_date">
    </div>
    <div class="mb-3">
      <textarea name="overview" class="form-control" placeholder="overview" required></textarea>
    </div>
    <div class="mb-3">
      <input type="text" name="company" class="form-control" required placeholder="company">
    </div>
    <select class="form-select mb-3" name="id_genre">
      <option selected disabled>genre</option>
      <?php foreach ($genres as $key => $genre) : ?>
        <option value="<?= $genre->id_genre ?>"><?= $genre->main_genre ?></option>
      <?php endforeach ?>        
    </select>
    <button type="submit" class="btn btn-primary">Confirm</button>
  </form>
</main>