<main class="container-fluid d-flex justify-content-center flex-wrap">
  <div class="card mt-3 border-secondary" style="max-width: 740px;">
    <div class="row g-0">
      <div class="col-md-6">
        <img src="https://image.tmdb.org/t/p/w1280<?= $movie->poster_path ?>" class="img-fluid rounded-start" alt="img movie">
      </div>
      <div class="col-md-6">
        <div class="card-body">
          <h5 class="card-title"><?= $movie->title ?></h5>
          <p class="card-text"><?= $movie->overview ?></p>
          <p class="card-text"><small class="text-body-secondary"><?= $movie->release_date ?></small></p>
        </div>
        <div class="card-body">
          <p class="card-text"><?= $movie->company ?></p>
          <a href="genre/<?= urlencode($movie->main_genre) ?>" class="card-link"><?= $movie->main_genre ?></a>
        </div>
      </div>
    </div>
  </div>
</main>