<main class="container-fluid mt-3 d-flex justify-content-center">
  <form action="login" method="post" class="text-center">
    <div class="mb-3">
      <input type="email" name="email" class="form-control" required placeholder="email">
    </div>
    <div class="mb-3">
      <input type="password" name="password" class="form-control" required placeholder="password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
</main>